"""
Pushbullet notification service for newsletter delivery.
"""
import aiohttp
import logging
from typing import List
from src.models.article import ContentItem

logger = logging.getLogger(__name__)


class PushbulletService:
    """Service for sending newsletters via Pushbullet."""

    API_URL = "https://api.pushbullet.com/v2/pushes"

    def __init__(self, config):
        self.api_key = config.PUSHBULLET_API_KEY

    async def send_newsletter(
        self,
        executive_summary: str,
        items: List[ContentItem],
        date_str: str
    ) -> bool:
        """
        Send the newsletter via Pushbullet.

        Args:
            executive_summary: The executive summary text
            items: List of top ContentItem objects
            date_str: Formatted date string for the title

        Returns:
            True if successful, False otherwise
        """
        title = f"Mortgage AI Daily - {date_str}"
        body = self._format_newsletter(executive_summary, items)

        headers = {
            "Access-Token": self.api_key,
            "Content-Type": "application/json"
        }

        payload = {
            "type": "note",
            "title": title,
            "body": body
        }

        try:
            timeout = aiohttp.ClientTimeout(total=30)
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(
                    self.API_URL,
                    json=payload,
                    headers=headers
                ) as resp:
                    if resp.status == 200:
                        logger.info("Newsletter sent successfully via Pushbullet")
                        return True
                    elif resp.status == 401:
                        logger.error("Pushbullet authentication failed - check API key")
                    elif resp.status == 429:
                        logger.error("Pushbullet rate limit exceeded (500 pushes/month)")
                    else:
                        error = await resp.text()
                        logger.error(f"Pushbullet error {resp.status}: {error[:200]}")
                    return False

        except aiohttp.ClientError as e:
            logger.error(f"Pushbullet connection error: {e}")
        except Exception as e:
            logger.error(f"Failed to send newsletter: {e}")

        return False

    def _format_newsletter(self, summary: str, items: List[ContentItem]) -> str:
        """Format the newsletter body."""
        lines = [
            "EXECUTIVE SUMMARY",
            "-" * 20,
            summary,
            "",
            "TOP 5 MORTGAGE AI INNOVATIONS",
            "-" * 30,
            ""
        ]

        for i, item in enumerate(items, 1):
            lines.append(f"{i}. {item.title}")
            lines.append(f"   Source: {item.source}")
            lines.append("")

            # Summary as bullet points
            if item.summary:
                # Split into sentences and format as bullets
                sentences = self._split_sentences(item.summary)
                for sentence in sentences[:2]:  # Max 2 sentences
                    if sentence.strip():
                        lines.append(f"   - {sentence.strip()}")
            elif item.description:
                lines.append(f"   - {item.description[:150]}...")

            lines.append("")
            lines.append(f"   Link: {item.url}")
            lines.append("")

        lines.append("-" * 30)
        lines.append("Generated by Mortgage AI Newsletter")

        return "\n".join(lines)

    def _split_sentences(self, text: str) -> List[str]:
        """Split text into sentences."""
        import re
        # Split on period, exclamation, or question mark followed by space
        sentences = re.split(r'(?<=[.!?])\s+', text)
        return [s for s in sentences if s.strip()]
